import Head from 'next/head'
import styled from 'styled-components'

export default function StyledComponentPage() {
  return (
    <div>
      <Head>
        <title>StyledComponents使ってみた</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Hero>
        <Title>
          Welcome to <a>StyledComponents</a>
        </Title>
      </Hero>
      <Container>
        <Main>
          <h2>StyledComponent?</h2>
          <p>
            JavaScript(TypeScript)のファイルにCSSを書けるようにしたもの。
            <br />
            1つのjs(ts)ファイルでレイアウトからスタイリングまで完結できる。
          </p>
          <h2>必要なライブラリ</h2>
          <ul>
            <li>styled-components</li>
            <li>@types/styled-components (TypeScript)</li>
            <li>babel-plugin-styled-components (Next)</li>
          </ul>
        </Main>
      </Container>
      <Footer>
        <p>footer</p>
      </Footer>
    </div>
  )
}

/*-------------- style --------------*/

const Container = styled.div`
  padding: 1rem;
  display: flex;
  justify-content: center;
`

const Hero = styled.div`
  min-height: 100vh;
  padding: 5rem 0.5rem;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  height: 100vh;
`

const Main = styled.main`
  min-width: 960px;
`

const Footer = styled.footer`
  width: 100%;
  height: 100px;
  border-top: 1px solid #eaeaea;
  display: flex;
  justify-content: center;
  align-items: center;
  a {
    display: flex;
    justify-content: center;
    align-items: center;
    flex-grow: 1;
  }
`

const Title = styled.h1`
  margin: 0;
  line-height: 1.15;
  font-size: 4rem;
  text-align: center;
  a {
    color: #0070f3;
    text-decoration: none;
  }
  a:hover,
  a:focus,
  a:active {
    text-decoration: underline;
  }
`
